name: generate files from kibot

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: INTI-CMNB/KiBot@v1_k6
        with:
          config: .github/workflows/resources/checks.kibot.yml
          schema: "{{ cookiecutter.project_slug }}.kicad_sch"
          board: "{{ cookiecutter.project_slug }}.kicad_pcb"
